- client/App.js
- server/routes/posts.mjs
> heart increases like count, got from db

- client/Screens/SignUpScreen.js
- client/package-lock.json
- client/package.json
- client/utils/hashingUtils.mjs
- server/routes/login.mjs
- server/routes/signup.mjs
Adding deterministic hashing functionality.
> fixing non-deterministic encryption problem

- .gitignore
- server/articles.mjs
- server/curl_test.sh
- server/generate_articles.js
- server/package-lock.json
- server/routes/login.mjs
Generating ten articles as our test data
> generating dummy articles

- .gitignore
- client/environment_variables.mjs
- server/utils/decryptionUtils.mjs
> minor fixes for server decryption utils

- client/App.js
- client/Screens/ContentPage.js
- client/Screens/LoginScreen.js
- client/Screens/SignUpScreen.js
- changed initial screen back to login screen
- successful login leads to community page
- changed MasonryList to FlatList until bug is fixed
- created popups with corresponding errors for unsuccessful login and signup
> Scrum 9/account creation response UI

- client/Screens/ContentPage.js
- client/components/Article.js
technically this is scrum 32 for mimi
> like count pulled from db

- client/redux/actions/likeAction.js
- client/redux/reducers/likeReducer.js
added like reducer and like action
> like button redux prep

- server/curl_test.sh
- server/routes/login.mjs
- server/routes/signup.mjs
> adding user info to login/signup responses

- server/curl_test.sh
- server/routes/signup.mjs
with the PR merged in, the frontend would not be able to use signup functionality until the SCRUM 73 is completed
> accepting all information

- client/Screens/SignUpScreen.js
- client/utils/format.mjs
> adding checks for formatting email and password

- client/Screens/ProfilePage.js
just the profile page component with a verify button and box for email input, no functionality, not connected to anything
> SCRUM 60 profile page component

- client/Screens/LoginScreen.js
- client/components/Article.js
- client/redux/actions/likeAction.js
- client/redux/reducers/likeReducer.js
scrum 32/38
like, unlike updates article like count in db
when logged in, liked articles are saved and will alr be liked upon next login
> SCRUM 32/38 like button functionality

- client/Screens/ContentPage.js
- client/Screens/LoginScreen.js
- client/components/Article.js
- client/components/profile_pages/AdminProfile.js
- client/components/profile_pages/UserProfile.js
- client/components/profile_pages/VendorProfile.js
- client/redux/actions/accountAction.js
- client/redux/reducers/accountReducer.js
- client/redux/store.js
Account type redux state and dispatcher set up, state is set upon login. 
Clicking on profile icon in nav bar will take you to 1 of 3 profile pages depending on account type.
3 profile page components have been created (1: admin, 2: vendor, 3: user)
> Scrum 59/61 profile page redux and nav

- client/Screens/ContentPage.js
- client/package.json
added correct version of webview to package.json and articles now filter according to selected tags when filter button is pressed
> filtered articles

- client/Screens/LoginScreen.js
- server/routes/login.mjs
- adding account_type to response json
- changing redux state update source
> adding account type

- client/Screens/LoginScreen.js
> SCRUM 117 changed login title to Log In

- client/Screens/ProfilePage.js
- client/components/profile_pages/AdminProfile.js
- client/components/profile_pages/VendorProfile.js
Admin account can now type in vendor email into input box to authorize them as vendors.
> Scrum 83/admin endpt

- client/Screens/LoginScreen.js
- client/components/Article.js
- client/redux/actions/likeAction.js
- client/redux/actions/saveAction.js
- client/redux/reducers/likeReducer.js
- client/redux/reducers/saveReducer.js
- client/redux/store.js
Saved button behaves the same as liked button, will show up if previously saved and logged in as user
> Scrum 89/save func

- client/Screens/CommunityScreen.js
- client/Screens/LoginScreen.js
- client/components/Article.js
- client/redux/actions/likeAction.js
- client/redux/actions/saveAction.js
- client/redux/reducers/likeReducer.js
- client/redux/reducers/saveReducer.js
- client/redux/store.js
save count is displayed under save button just like like button, but only if user is admin account type 1
adjusted the CSS styles to conditionally change bottom padding of save button to make room for count text, hardcoded :(
> Scrum 101/save count

- client/App.js
- client/Screens/ProfilePage.js
- client/components/Article.js
- client/components/NavBar.js
“If user is not logged in, profile page should show the login page” doing this instead because profile page has been unlinked from community screen alr
BUG FIX: alert/redirect users if they’re not logged in and try to like
BUG FIX: default screen is now community screen
> SCRUM 81: nav changes made

- client/Screens/ProfilePage.js
- client/components/Article.js
- client/components/NavBar.js
> small comments and fixes

- client/App.js
- client/Screens/CommunityScreen.js
- client/Screens/SavedArticles.js
- client/components/Article.js
- client/components/NavBar.js
and populates correctly with only saved articles!
> saved content ui linked to nav bar

- client/Screens/LoginScreen.js
- client/Screens/SavedArticles.js
- client/Screens/SignUpScreen.js
- client/components/Article.js
- client/components/profile_pages/UserProfile.js
- client/components/profile_pages/VendorProfile.js
- client/redux/actions/vendAction.js
- client/redux/reducers/vendReducer.js
- client/redux/store.js
- server/routes/login.mjs
Vendor acct init redux state created
getVend action is dispatched upon login
setVend will be dispatched in next ticket
Copy pasted user profile page code into vendor profile page, hardcoded some titles so that I can work on my next ticket
Bug fixes:
- server/login.mjs had a bug
- renamed some things
- navigation.replace and stuff throw occasional errors but wtv ignore them, they don't break anything
> SCRUM 139: bug fixes + vend redux

- client/components/profile_pages/VendorProfile.js
Dispatch redux state and set to true for vendor acct initialized when profile page edit changes are saved, this can be changed depending on how Mimi implements vendor profile page
also vendor profile page code updated with Vindhya's prof pg changes to stay up to date
> SCRUM 140: update redux state when changes saved

- client/Screens/LoginScreen.js
- client/Screens/ProfilePage.js
- client/components/profile_pages/AdminProfile.js
- client/components/profile_pages/UserProfile.js
- client/components/profile_pages/VendorProfile.js
- server/routes/posts.mjs
- admin profile can update profile pic successfully
- user info can be updated from admin or user profile screen and saves to backend 
- general user profile pulls data from backend
- vendor profile pulls name from backend
> Scrum 130/change account info bug

- client/Screens/ProfilePage.js
- client/components/Article.js
deleted some commented out things
> initial commit
